cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from mysite.core import views as core_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    url(r'^about/',core_views.about, name='about'),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^product_list/$', core_views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', core_views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',core_views.product_detail,name='product_detail'),

]
admin.site.site_header = settings.ADMIN_SITE_HEADER
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

mysite/core/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django_resized import ResizedImageField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category', args=[self.slug])




class Productdb(models.Model):

    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = ResizedImageField(size=[300, 300], upload_to='products/%Y/%m/%d', blank=True)
    # image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id, self.slug])

class About(models.Model):
    image = ResizedImageField(size=[300, 300], upload_to='products/%Y/%m/%d', blank=True)
    name = models.CharField(max_length=200, db_index=True)
    description = models.CharField(max_length=2000, db_index=True)

    def __str__(self):
        return self.name

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mysite.core.models import Category,Productdb
from django.views.decorators.csrf import csrf_protect
from .cart import Cart
from django.shortcuts import render
from .forms import CartAddProductForm
from django.core.mail import send_mail
from django.conf import settings

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Productdb, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Productdb, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart_detail.html', {'cart': cart})

def sendemail(request):
	print ("email sent")
	send_mail('hello','order recieved', settings.EMAIL_HOST_USER,['sayantikabanik122@gmail.com'],fail_silently=False)
#	return redirect('cart:cart_detail')
@csrf_protect
def login(request):
     csrfContext = RequestContext(request)
     return render_to_response('cart_detail.html', csrfContext)

mysite/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from mysite.core.models import Productdb,Category,About
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm


@login_required
def home(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Productdb.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'home.html', {'category': category,
                                                          'categories': categories,
                                                          'products': products})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Productdb.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Productdb, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

def about(request):
    about_list = About.objects.all()
    about_dict = {"about_records":about_list}
    return render(request,'about.html',about_dict)

mysite/templates/about.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
<div class="jumbotron " style= "text-align :center">
  <h1 style="font-family: verdana;font-weight: bold;">About our products</hi>
</div >
<br>
<br>

        <div class="Teeth_div">
          {% if about_records %}

                {% for acc in about_records %}

                  <div class="jumbotron " >
                    <div class="row">
                      <div class="col-xs-4">
                      <!-- <img src= "{% static "images/prostethics.jpg" %}" alt="Uh Oh, didn't show!"> -->
                      <img src="{% if acc.image %}{{ acc.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </div>
                      <div class="col-xs-8">
                    <p>Name                  : <span style="font-family: verdana ; "> {{ acc.name }} </span></p>

                    <p>Description                   :  <span  style="font-family: verdana">  {{ acc.description }} </span></p>
                  </div>
                </div>
                    <hr style="display: block;height: 1px;border: 0;border-top: 1px solid #ccc;margin: 1em 0;padding: 0;">
                  </div>

                {% endfor %}


          {% else %}
            <p>No Access Records. Table Not Created.</p>
          {% endif %}
        </div>
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static "css/base.css" % }"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>


<body>

  <nav class="navbar  large navbar navbar-inverse bg-inverse" style= "width:100% ; margin: 0 auto;background-color:#000000">

      <div class="container">

            <ul class="nav navbar-nav ">

          <li ><a class ="navbar-brand " href="{% url 'home' %}">Welcome to jeevan</a></li>

</ul>
<ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}

            <li><a class="navbar-link" href="{% url 'about' %}"></span>About Products</a></li>
              <li><a class ="navbar-link " href="{% url 'logout' %}"><span class="glyphicon glyphicon-user"></span>logout</a></li>
            {% else %}
            <li><a class ="navbar-link"href="{% url 'login' %}">login</a></li>
             <li><a class ="navbar-link"href="{% url 'signup' %}">signup</a></li>
            {% endif %}
          </ul>
</div>



    </nav>



      <div class="container" style="height :100% ">
        <main>
          {% block content %}
          {% endblock %}
        </main>
      </div>
    </div>
  </body>
</html>

mysite/templates/cart_detail.html
{% extends "base.html" %}
{% load static %}




{% block title %}
    Your cart
{% endblock %}

{% block content %}



  

        <div class="container">
        <h2>Your Cart</h2>

        <table class="table">
          <thead>
            <tr>
              <th>Image</th>
              <th>Product</th>
              <th>Quantity</th>
              <th>Remove</th>
              <th>Unit Price</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                <tr>
    <td><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"></td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price }}</td>
            </tr>
            </tbody>
        </table>
      </div>
      <p class="text-right">
          <a href="{% url "home" %}" class="button light" style="color: blue; font-weight: bold; " >Continue shopping</a> 
<div align="center">
	<button class="btn btn-primary" style="width:30%" type="submit", onclick="fun()">Submit</button>
<script>
	function fun(){
	alert("Thanks for visiting us!");
}
</script>
</div>

<!--
<div align="left">
	<button type="submit",onClick="email()">Send mail</button>
<script>
function email(){

emailjs.send("gmail","template_jpKYdkOi",{name: "James", notes: "Check this out!"});</script>
	</div>-->
  <br>
  </br>
  <br></br><br></br>
  <div class="container" align="middle">
<h1 style="font-family:verdana; color: red;">Confirm your order</h1>
  <form id="myform" method="post">
  
  <input style="width:70%" placeholder="Reply to" type="text" name="reply_to" alt="Send to" />
<br></br>
  <input style="width:70%"  placeholder="From" type="text" name="from_name" alt="From" />
  <br><br>
  <button class="btn btn-primary" style="width:30%">
  Send
  </button>
  {%csrf_token%}
  </form>
</div>
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  <script type="text/javascript" src="https://cdn.emailjs.com/dist/email.min.js"></script>
  <script type="text/javascript">
     (function(){
        emailjs.init("user_3WBB9ACqZT9Xz69YPl8rK");
     })();
  </script>
  <script>
  var myform = $("form#myform");
  myform.submit(function(event){
  	event.preventDefault();

    // Change to your service ID, or keep using the default service
    var service_id = "gmail";
    var template_id = "template_Cfid9V41";

    myform.find("button").text("Sending...");
    emailjs.sendForm(service_id,template_id,"myform")
    	.then(function(){
      	alert("Sent!");
         myform.find("button").text("Send");
      }, function(err) {
         alert("Send email failed!\r\n Response:\n " + JSON.stringify(err));
         myform.find("button").text("Send");
      });
    return false;
  });</script>

</body>
{% endblock %}

mysite/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

mysite/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<style>
.button5 {
    background-color: #E9E9E9;
    color: black;
    border: 2px solid #555555;
}

.button5:hover {
    background-color: black;
    color: white;
}
</style>

<div class="pull-right" >
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            <h4>Your cart:</h4>
            <a href="{% url "cart:cart_detail" %}">
                <h4>{{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}</h4>
            </a>
        {% else %}
            <h4>Your cart is empty</h4>
        {% endif %}
    {% endwith %}
</div>
    <div class ="jumbotron" style= "text-align :center ; margin :0 auto">
        <h1>Categories</h1>
      </div>
       <div class="container" style= "text-align :center ; margin :0 auto">
        <ul>
            <h1  {% if not category %}class="selected"{% endif %}>
                <a class="navbar-link" href="{% url "product_list" %}"><button type="button" class="button button5 btn btn-primary " style="height:50px;width:500px">All</button></a>
            </h1>
        {% for c in categories %}
            <h1 {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}"><button type="button" class="button button5 btn btn-primary " style="height:50px;width:500px">{{c.name}}</button></a>
            </h1>
        {% endfor %}
        </ul>
</div>
{% endblock %}

mysite/templates/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<div class="pull-right" >
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            <h4>Your cart:</h4>
            <a href="{% url "cart:cart_detail" %}">
                <h4>{{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}</h4>
            </a>
        {% else %}
            <h4>Your cart is empty</h4>
        {% endif %}
    {% endwith %}
</div>

    <div class ="container">
      <div class ="jumbotron" style= "text-align :center ; margin :0 auto">


        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        </div>
        <br>
        <br>
        {% for product in products %}
            <div class="row">
              <div class="col-xs-4">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
              </div>
              <div class="col-xs-8">
                <h1><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h1><br>
                ${{ product.price }}<br>
                <br>
                {{ product.description|linebreaks }}
              </div>
            </div>


                 <hr style="display: block;height: 1px;border: 0;border-top: 1px solid #ccc;margin: 1em 0;padding: 0;">


        {% endfor %}
    </div>
{% endblock %}

mysite/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<style>
body  {
    background-image: url("https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/BYjxg9jTitpfkf6g/gray-white-shine-background-bright-christmas-design-glamour-glow-holiday_stsch8xvl_thumbnail-full01.png");
    background-color: #cccccc;
}
</style>

	<!-- <img src="{% static "images/coverpic.jpg" %}" alt="cant'load"/> -->
  {% if form.errors %}
   <div style="background-color:yellow"; height= 30px>
    <p style="color: red">Your username and password didn't match. Please try again.</p>
</div>
  {% endif %}
  <div class="jumbotron">
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <p>
      <p>
    <a style="color:#000000;" href="{% url 'signup' %}">New to My Site? Sign up</a>

  </form>
  </div>
{% endblock %}

mysite/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<style>
body  {
    background-image: url("https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/BYjxg9jTitpfkf6g/gray-white-shine-background-bright-christmas-design-glamour-glow-holiday_stsch8xvl_thumbnail-full01.png");
    background-color: #cccccc;
}
</style>
<div class="jumbotron">
  <h2 style="font-weight: bold;">Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
  </div>
{% endblock %}